### ISSUE TITLE
RVAs and INTs for Build 3028.0

### ISSUE THREAD

**Issue by MoneyWasted** [DaniTRDev/ezGTAUnpacker#1]
Do you have the latest RVAs and INTs for the latest game build?

I would like to learn how you get these values so I can get them for past and future game builds. So don't have to keep opening issues.

**Comment by DaniTRDev** [comment]
I have already updated the repo. You'll only need to move the new 'data.json' to 'bin' foder and it'll work again.

**Comment by DaniTRDev** [comment]
If you test it and something goes wrong open a new issue please.
